# conda env create -f environment.yml
name: nlp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
platforms:
  - linux-64
dependencies:
  - python=3.11.6
  - pdbpp
  - chromadb
  - gensim
  - huggingface_hub[cli]
  - numpy<2 # for now (many legacy libs don't work with newest)
  - langchain
  - langchain-community
  - langchain-openai
  - nameparser
  - networkx
  - openai
  - pandoc
  - sumy
  - textblob
  - wordcloud # visualization for tokens in a document
  - yake
  - yfinance
  - vdom
  # text conversion
  - html2text
  # training
  - sentence-transformers # sentences -> encoding generator
  - tiktoken # Byte Pair Encoding (BPE) tokenizer (from OpenAI)
  - word2vec # basic token -> encoding generator
  - ffmpeg
  - ctransformers[cuda]
  # torch
  - pytorch:pytorch
  - pytorch:torchvision
  - pytorch:torchaudio
  - nvidia:cudatoolkit=11.8
  - nvidia:pytorch-cuda=12.1
  - faiss-gpu=1.7.2
  # classic libs
  - pandas
  - matplotlib
  - scipy
  - seaborn
  - scikit-learn
  - nltk
  # utils
  - bs4
  - click
  - openpyxl
  - python-dotenv
  - sqlalchemy
  # pip/pypi
  - pip
  - pip:
    - aider-chat
    - contractions
    - keybert
    - mammoth # used for docx to html
    - more-itertools
    - number-parser
    - textacy
    - transformers==4.36.2
    # - git+git://github.com/bissli/NLPre@master
    - openai-whisper
    - pytube
    - accelerate
    # testing
    - asserts
    # torch (non-gpu)
    # - --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/xpu/us/
    # - torch==2.1.0.post0+cu117
    # - torchvision==0.16.0.post0
    # - torchaudio==2.1.0.post0
    # - intel-extension-for-pytorch==2.1.20+xpu
    # - oneccl_bind_pt==2.1.200+xpu
